### ISSUE TITLE
import.meta.url

### ISSUE THREAD

**Issue by FranklinYu** [zoutepopcorn/bapkg#1]
Any successful example using `import.meta.url`? `__dirname` is not available in ES Module IIUC.

**Comment by zoutepopcorn** [comment]
Ah sorry I'm not familiair with that. Do you have any error or possible solution?

**Comment by FranklinYu** [comment]
Sorry I misunderstood this repository. I found that it's using Babel so this is really Babel's fault. Babel only has [`@babel/plugin-syntax-import-meta`](https://babeljs.io/docs/en/babel-plugin-syntax-import-meta) which is a [syntax plugin](https://babeljs.io/docs/en/plugins#syntax-plugins) that don't do any transformation.
